minimumReleaseAgeExclude:
  - '@rspress/core@2.0.16 || 2.0.18 || 2.0.19'
  - '@rspress/plugin-playground@2.0.16 || 2.0.18 || 2.0.19'
  - '@rspress/plugin-preview@2.0.16 || 2.0.18 || 2.0.19'
  - '@rspress/shared@2.0.16 || 2.0.18 || 2.0.19'
  - '@rspress/plugin-llms@2.0.18 || 2.0.19'
  - '@types/node@26.1.2'
  - '@types/react@19.2.18'
  - '@shikijs/core@4.4.2'
  - '@shikijs/primitive@4.4.2'
  - '@shikijs/transformers@4.4.2'
  - '@shikijs/types@4.4.2'
